In [1]:
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime

In [2]:
path='attendence'
images=[]
classNames=[]
mylist=os.listdir(path)
print(mylist)
for cl in mylist:
    curImg=cv2.imread(f'{path}/{cl}')
    images.append(curImg)
    classNames.append(os.path.splitext(cl)[0])
print(classNames)

['Balajiiii.jpg', 'Bill_Gates.jpg', 'elon.jpg', 'elon2.jpg']
['Balajiiii', 'Bill_Gates', 'elon', 'elon2']


In [3]:
def findencoadings(images):
    encodelist=[]
    for img in images:
        img=cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        encode=face_recognition.face_encodings(img)[0]
        encodelist.append(encode)
    return encodelist

def markAttendence(name):
    with open('attendence.csv','r+')as f:
        myDataList=f.readlines()
        namelist=[]
        for line in myDataList:
            entry = line.split(',')
            namelist.append(entry[0])
        if name not in namelist:
            now=datetime.now()
            dtString=now.strftime('%H:%M:%S')
            f.writelines(f'\n{name},{dtString}')
        
        print(myDataList)
        
        
        
        


encodeListKnown=findencoadings(images)
print('Encoding complete')


Encoding complete


In [4]:
cap=cv2.VideoCapture(0)
while True:
    success, img=cap.read()
    imgS=cv2.resize(img,(0,0),None,0.25,0.25)
    img=cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    
    facesCurFrame=face_recognition.face_locations(imgS)
    encodescurFrame=face_recognition.face_encodings(imgS,facesCurFrame)
    
    for encodeFace,faceLoc in zip(encodescurFrame,facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown,encodeFace)
        faceDis = face_recognition.face_distance(encodeListKnown,encodeFace)
        print(faceDis)
        matchIndex=np.argmin(faceDis)
        
        if matches[matchIndex]:
            name=classNames[matchIndex].upper()
            print(name)
            y1,x2,y2,x1=faceLoc
            y1,x2,y2,x1=y1*4,x2*4,y2*4,x1*4
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
            cv2.rectangle(img,(x1,y2-35),(x2,y2),(0,255,0),cv2.FILLED)
            cv2.putText(img,name,(x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)
            markAttendence(name)
    
    cv2.imshow('webcame',img)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    

[0.53282238 0.85507227 0.76559596 0.79452734]
BALAJIIII
['Name,Time\n', 'ELON,20:37:02\n', 'BILL_GATES,20:37:08\n', 'BALAJIIII,20:37:23\n', 'RAJ,20:37:59']
[0.49987458 0.84082201 0.85426295 0.84689746]
BALAJIIII
['Name,Time\n', 'ELON,20:37:02\n', 'BILL_GATES,20:37:08\n', 'BALAJIIII,20:37:23\n', 'RAJ,20:37:59']
[0.54005284 0.88442913 0.87008962 0.8765088 ]
BALAJIIII
['Name,Time\n', 'ELON,20:37:02\n', 'BILL_GATES,20:37:08\n', 'BALAJIIII,20:37:23\n', 'RAJ,20:37:59']
[0.48740097 0.90114093 0.89265974 0.88016306]
BALAJIIII
['Name,Time\n', 'ELON,20:37:02\n', 'BILL_GATES,20:37:08\n', 'BALAJIIII,20:37:23\n', 'RAJ,20:37:59']
[0.48972501 0.88015703 0.90431945 0.88989263]
BALAJIIII
['Name,Time\n', 'ELON,20:37:02\n', 'BILL_GATES,20:37:08\n', 'BALAJIIII,20:37:23\n', 'RAJ,20:37:59']
[0.74942966 0.84017662 0.8262531  0.81968376]
[0.50546577 0.88818302 0.83364447 0.8459099 ]
BALAJIIII
['Name,Time\n', 'ELON,20:37:02\n', 'BILL_GATES,20:37:08\n', 'BALAJIIII,20:37:23\n', 'RAJ,20:37:59']
[0.57262101 0.8479

[0.52387136 0.86664161 0.87223844 0.88689495]
BALAJIIII
['Name,Time\n', 'ELON,20:37:02\n', 'BILL_GATES,20:37:08\n', 'BALAJIIII,20:37:23\n', 'RAJ,20:37:59']
[0.5311782  0.84608369 0.86252182 0.87894506]
BALAJIIII
['Name,Time\n', 'ELON,20:37:02\n', 'BILL_GATES,20:37:08\n', 'BALAJIIII,20:37:23\n', 'RAJ,20:37:59']
[0.51583852 0.83021325 0.83622479 0.86672944]
BALAJIIII
['Name,Time\n', 'ELON,20:37:02\n', 'BILL_GATES,20:37:08\n', 'BALAJIIII,20:37:23\n', 'RAJ,20:37:59']
[0.5017009  0.85882884 0.86463596 0.87823335]
BALAJIIII
['Name,Time\n', 'ELON,20:37:02\n', 'BILL_GATES,20:37:08\n', 'BALAJIIII,20:37:23\n', 'RAJ,20:37:59']
[0.4976428  0.8482654  0.83198757 0.85994692]
BALAJIIII
['Name,Time\n', 'ELON,20:37:02\n', 'BILL_GATES,20:37:08\n', 'BALAJIIII,20:37:23\n', 'RAJ,20:37:59']
[0.54592767 0.83196981 0.8329763  0.86792372]
BALAJIIII
['Name,Time\n', 'ELON,20:37:02\n', 'BILL_GATES,20:37:08\n', 'BALAJIIII,20:37:23\n', 'RAJ,20:37:59']
[0.51381002 0.88147476 0.84878212 0.87948778]
BALAJIIII
['Name,T